/**
 * Built-in stickers: a selection of Fluent Emoji 3D (Microsoft, MIT licence),
 * 256 px WebP in `src/assets/stickers/fluent/`. Stored in notes as
 * `fluent/<id>` (the upstream file name). Keywords: French label first, then
 * search words; same for English.
 */
export type StickerCategory = "nature" | "food" | "travel" | "objects";

export interface CatalogEntry {
  id: string;
  category: StickerCategory;
  /** Unicode code points of the emoji (file of the upstream package). */
  code: string;
  fr: string;
  en: string;
}

type Row = [id: string, code: string, fr: string, en: string];

const NATURE: Row[] = [
  ["fallen_leaf", "1f342", "feuille morte, automne", "fallen leaf, autumn"],
  ["maple_leaf", "1f341", "feuille d'érable, automne", "maple leaf, autumn"],
  ["cherry_blossom", "1f338", "fleur de cerisier, printemps", "cherry blossom, spring"],
  ["sunflower", "1f33b", "tournesol, fleur, été", "sunflower, flower, summer"],
  ["potted_plant", "1fab4", "plante en pot", "potted plant"],
  ["mushroom", "1f344", "champignon, forêt", "mushroom, forest"],
  ["cactus", "1f335", "cactus, désert", "cactus, desert"],
  ["herb", "1f33f", "herbe, plante", "herb, plant"],
  ["sun", "2600-fe0f", "soleil, beau temps", "sun, sunny, weather"],
  ["crescent_moon", "1f319", "croissant de lune, nuit", "crescent moon, night"],
  ["rainbow", "1f308", "arc-en-ciel", "rainbow"],
  ["snowflake", "2744-fe0f", "flocon, neige, hiver", "snowflake, snow, winter"],
  ["tulip", "1f337", "tulipe, fleur", "tulip, flower"],
  ["rose", "1f339", "rose, fleur", "rose, flower"],
  ["hibiscus", "1f33a", "hibiscus, fleur", "hibiscus, flower"],
  ["blossom", "1f33c", "fleur", "blossom, flower"],
  ["bouquet", "1f490", "bouquet, fleurs", "bouquet, flowers"],
  ["four_leaf_clover", "1f340", "trèfle à quatre feuilles, chance", "four leaf clover, luck"],
  ["leaf_fluttering_in_wind", "1f343", "feuilles au vent", "leaves, wind"],
  ["seedling", "1f331", "pousse, jardin", "seedling, garden"],
  ["palm_tree", "1f334", "palmier", "palm tree"],
  ["evergreen_tree", "1f332", "sapin, arbre", "evergreen, tree"],
  ["deciduous_tree", "1f333", "arbre", "tree"],
  ["rock", "1faa8", "pierre, caillou", "rock, stone"],
  ["wood", "1fab5", "bois, bûche", "wood, log"],
  ["sun_with_face", "1f31e", "soleil souriant", "sun with face"],
  ["star", "2b50", "étoile", "star"],
  ["glowing_star", "1f31f", "étoile brillante", "glowing star"],
  ["sparkles", "2728", "étincelles, magie", "sparkles, magic"],
  ["cloud", "2601-fe0f", "nuage", "cloud"],
  ["sun_behind_cloud", "26c5", "soleil et nuage, météo", "sun behind cloud, weather"],
  ["umbrella_with_rain_drops", "2614", "parapluie, pluie", "umbrella, rain"],
  ["snowman", "26c4", "bonhomme de neige, hiver", "snowman, winter"],
  ["droplet", "1f4a7", "goutte, eau", "droplet, water"],
  ["fire", "1f525", "feu, flamme", "fire, flame"],
  ["high_voltage", "26a1", "éclair, énergie", "high voltage, lightning"],
  ["cat_face", "1f431", "chat", "cat"],
  ["dog_face", "1f436", "chien", "dog"],
  ["fox", "1f98a", "renard", "fox"],
  ["bear", "1f43b", "ours", "bear"],
  ["rabbit_face", "1f430", "lapin", "rabbit"],
  ["hedgehog", "1f994", "hérisson", "hedgehog"],
  ["owl", "1f989", "chouette, hibou", "owl"],
  ["bird", "1f426", "oiseau", "bird"],
  ["butterfly", "1f98b", "papillon", "butterfly"],
  ["lady_beetle", "1f41e", "coccinelle", "ladybug, lady beetle"],
  ["honeybee", "1f41d", "abeille", "honeybee, bee"],
  ["snail", "1f40c", "escargot", "snail"],
  ["turtle", "1f422", "tortue", "turtle"],
  ["tropical_fish", "1f420", "poisson tropical", "tropical fish"],
  ["spouting_whale", "1f433", "baleine", "whale"],
  ["octopus", "1f419", "pieuvre", "octopus"],
  ["frog", "1f438", "grenouille", "frog"],
  ["penguin", "1f427", "manchot, pingouin", "penguin"],
  ["unicorn", "1f984", "licorne", "unicorn"],
];

const FOOD: Row[] = [
  ["hot_beverage", "2615", "café, boisson chaude", "coffee, hot beverage"],
  ["croissant", "1f950", "croissant, petit-déjeuner", "croissant, breakfast"],
  ["teacup_without_handle", "1f375", "thé, tasse", "tea, teacup"],
  ["bubble_tea", "1f9cb", "thé aux perles", "bubble tea"],
  ["baguette_bread", "1f956", "baguette, pain", "baguette, bread"],
  ["bread", "1f35e", "pain", "bread"],
  ["cheese_wedge", "1f9c0", "fromage", "cheese"],
  ["egg", "1f95a", "œuf", "egg"],
  ["cooking", "1f373", "œuf au plat, cuisine", "cooking, fried egg"],
  ["pancakes", "1f95e", "crêpes, pancakes", "pancakes"],
  ["waffle", "1f9c7", "gaufre", "waffle"],
  ["pizza", "1f355", "pizza", "pizza"],
  ["hamburger", "1f354", "hamburger", "hamburger, burger"],
  ["french_fries", "1f35f", "frites", "french fries"],
  ["taco", "1f32e", "taco", "taco"],
  ["sandwich", "1f96a", "sandwich", "sandwich"],
  ["spaghetti", "1f35d", "spaghetti, pâtes", "spaghetti, pasta"],
  ["steaming_bowl", "1f35c", "bol fumant, ramen, soupe", "steaming bowl, ramen, soup"],
  ["sushi", "1f363", "sushi", "sushi"],
  ["bento_box", "1f371", "bento", "bento box"],
  ["dumpling", "1f95f", "ravioli, gyoza", "dumpling"],
  ["green_salad", "1f957", "salade", "salad"],
  ["avocado", "1f951", "avocat", "avocado"],
  ["tomato", "1f345", "tomate", "tomato"],
  ["carrot", "1f955", "carotte", "carrot"],
  ["ear_of_corn", "1f33d", "maïs", "corn"],
  ["hot_pepper", "1f336-fe0f", "piment", "hot pepper, chili"],
  ["broccoli", "1f966", "brocoli", "broccoli"],
  ["red_apple", "1f34e", "pomme", "apple"],
  ["pear", "1f350", "poire", "pear"],
  ["tangerine", "1f34a", "mandarine, orange", "tangerine, orange"],
  ["lemon", "1f34b", "citron", "lemon"],
  ["banana", "1f34c", "banane", "banana"],
  ["watermelon", "1f349", "pastèque", "watermelon"],
  ["grapes", "1f347", "raisin", "grapes"],
  ["strawberry", "1f353", "fraise", "strawberry"],
  ["cherries", "1f352", "cerises", "cherries"],
  ["peach", "1f351", "pêche", "peach"],
  ["pineapple", "1f34d", "ananas", "pineapple"],
  ["kiwi_fruit", "1f95d", "kiwi", "kiwi"],
  ["birthday_cake", "1f382", "gâteau d'anniversaire", "birthday cake"],
  ["shortcake", "1f370", "part de gâteau", "cake, shortcake"],
  ["cupcake", "1f9c1", "cupcake", "cupcake"],
  ["doughnut", "1f369", "beignet, donut", "doughnut, donut"],
  ["cookie", "1f36a", "cookie, biscuit", "cookie"],
  ["chocolate_bar", "1f36b", "chocolat", "chocolate"],
  ["lollipop", "1f36d", "sucette", "lollipop"],
  ["ice_cream", "1f368", "glace", "ice cream"],
  ["soft_ice_cream", "1f366", "glace italienne", "soft ice cream"],
  ["honey_pot", "1f36f", "miel", "honey"],
  ["wine_glass", "1f377", "vin, verre", "wine glass"],
  ["clinking_glasses", "1f942", "trinquer, champagne", "clinking glasses, cheers"],
  ["tropical_drink", "1f379", "cocktail", "tropical drink, cocktail"],
  ["bottle_with_popping_cork", "1f37e", "bouteille, fête", "bottle, celebration"],
];

const TRAVEL: Row[] = [
  ["airplane", "2708-fe0f", "avion, vol", "airplane, flight"],
  ["rocket", "1f680", "fusée", "rocket"],
  ["automobile", "1f697", "voiture", "car, automobile"],
  ["bus", "1f68c", "bus", "bus"],
  ["high-speed_train", "1f684", "train, TGV", "high-speed train"],
  ["bicycle", "1f6b2", "vélo", "bicycle, bike"],
  ["motor_scooter", "1f6f5", "scooter", "scooter"],
  ["kick_scooter", "1f6f4", "trottinette", "kick scooter"],
  ["sailboat", "26f5", "voilier, bateau", "sailboat"],
  ["ship", "1f6a2", "paquebot, bateau", "ship"],
  ["helicopter", "1f681", "hélicoptère", "helicopter"],
  ["parachute", "1fa82", "parachute", "parachute"],
  ["world_map", "1f5fa-fe0f", "carte du monde", "world map"],
  ["compass", "1f9ed", "boussole", "compass"],
  ["luggage", "1f9f3", "valise, bagage", "luggage, suitcase"],
  ["backpack", "1f392", "sac à dos", "backpack"],
  ["camping", "1f3d5-fe0f", "camping", "camping"],
  ["tent", "26fa", "tente", "tent"],
  ["mountain", "26f0-fe0f", "montagne", "mountain"],
  ["snow-capped_mountain", "1f3d4-fe0f", "montagne enneigée", "snow-capped mountain"],
  ["mount_fuji", "1f5fb", "mont Fuji, Japon", "mount fuji, japan"],
  ["volcano", "1f30b", "volcan", "volcano"],
  ["beach_with_umbrella", "1f3d6-fe0f", "plage, parasol", "beach, umbrella"],
  ["desert_island", "1f3dd-fe0f", "île déserte", "desert island"],
  ["sunrise", "1f305", "lever de soleil", "sunrise"],
  ["sunset", "1f307", "coucher de soleil, ville", "sunset, city"],
  ["night_with_stars", "1f303", "nuit étoilée, ville", "night with stars"],
  ["cityscape", "1f3d9-fe0f", "ville, immeubles", "cityscape, city"],
  ["house", "1f3e0", "maison", "house, home"],
  ["house_with_garden", "1f3e1", "maison avec jardin", "house with garden"],
  ["classical_building", "1f3db-fe0f", "monument, musée", "classical building, museum"],
  ["statue_of_liberty", "1f5fd", "statue de la Liberté, New York", "statue of liberty, new york"],
  ["tokyo_tower", "1f5fc", "tour de Tokyo", "tokyo tower"],
  ["castle", "1f3f0", "château", "castle"],
  ["japanese_castle", "1f3ef", "château japonais", "japanese castle"],
  ["ferris_wheel", "1f3a1", "grande roue", "ferris wheel"],
  ["roller_coaster", "1f3a2", "montagnes russes", "roller coaster"],
  ["carousel_horse", "1f3a0", "manège", "carousel"],
  ["fountain", "26f2", "fontaine", "fountain"],
  ["moai", "1f5ff", "moaï, île de Pâques", "moai, easter island"],
  ["camera", "1f4f7", "appareil photo", "camera"],
  ["camera_with_flash", "1f4f8", "photo, flash", "camera with flash"],
  ["ticket", "1f3ab", "ticket, billet", "ticket"],
  ["admission_tickets", "1f39f-fe0f", "billets d'entrée", "admission tickets"],
  ["round_pushpin", "1f4cd", "épingle, lieu", "round pushpin, location"],
  ["globe_showing_europe-africa", "1f30d", "globe, Europe", "globe, europe"],
  ["sunglasses", "1f576-fe0f", "lunettes de soleil", "sunglasses"],
  ["hiking_boot", "1f97e", "chaussure de randonnée", "hiking boot"],
  ["umbrella_on_ground", "26f1-fe0f", "parasol", "beach umbrella"],
  ["diving_mask", "1f93f", "masque de plongée", "diving mask, snorkel"],
];

const OBJECTS: Row[] = [
  ["books", "1f4da", "livres", "books"],
  ["open_book", "1f4d6", "livre ouvert, lecture", "open book, reading"],
  ["notebook", "1f4d3", "carnet", "notebook"],
  ["notebook_with_decorative_cover", "1f4d4", "carnet décoré", "notebook, decorative"],
  ["memo", "1f4dd", "mémo, notes", "memo, notes"],
  ["pencil", "270f-fe0f", "crayon", "pencil"],
  ["fountain_pen", "1f58b-fe0f", "stylo plume", "fountain pen"],
  ["crayon", "1f58d-fe0f", "crayon de couleur", "crayon"],
  ["paintbrush", "1f58c-fe0f", "pinceau", "paintbrush"],
  ["artist_palette", "1f3a8", "palette, peinture", "artist palette, painting"],
  ["scissors", "2702-fe0f", "ciseaux", "scissors"],
  ["paperclip", "1f4ce", "trombone", "paperclip"],
  ["straight_ruler", "1f4cf", "règle", "ruler"],
  ["spiral_calendar", "1f5d3-fe0f", "calendrier", "calendar"],
  ["alarm_clock", "23f0", "réveil", "alarm clock"],
  ["hourglass_done", "231b", "sablier", "hourglass"],
  ["light_bulb", "1f4a1", "ampoule, idée", "light bulb, idea"],
  ["candle", "1f56f-fe0f", "bougie", "candle"],
  ["laptop", "1f4bb", "ordinateur portable", "laptop"],
  ["mobile_phone", "1f4f1", "téléphone", "mobile phone"],
  ["headphone", "1f3a7", "casque, musique", "headphones, music"],
  ["musical_notes", "1f3b6", "notes de musique", "musical notes"],
  ["guitar", "1f3b8", "guitare", "guitar"],
  ["wrapped_gift", "1f381", "cadeau", "gift, present"],
  ["balloon", "1f388", "ballon, fête", "balloon, party"],
  ["party_popper", "1f389", "fête, cotillons", "party popper, celebration"],
  ["confetti_ball", "1f38a", "confettis", "confetti"],
  ["trophy", "1f3c6", "trophée", "trophy"],
  ["sports_medal", "1f3c5", "médaille", "medal"],
  ["crown", "1f451", "couronne", "crown"],
  ["gem_stone", "1f48e", "diamant, pierre précieuse", "gem stone, diamond"],
  ["red_heart", "2764-fe0f", "cœur, amour", "heart, love"],
  ["sparkling_heart", "1f496", "cœur étincelant", "sparkling heart"],
  ["key", "1f511", "clé", "key"],
  ["magnifying_glass_tilted_left", "1f50d", "loupe, recherche", "magnifying glass, search"],
  ["envelope", "2709-fe0f", "enveloppe, courrier", "envelope, mail"],
  ["love_letter", "1f48c", "lettre d'amour", "love letter"],
  ["package", "1f4e6", "colis", "package, parcel"],
  ["bell", "1f514", "cloche, rappel", "bell, reminder"],
  ["money_bag", "1f4b0", "argent, budget", "money bag, budget"],
  ["shopping_bags", "1f6cd-fe0f", "courses, shopping", "shopping bags"],
  ["teddy_bear", "1f9f8", "ours en peluche", "teddy bear"],
  ["puzzle_piece", "1f9e9", "pièce de puzzle", "puzzle piece"],
  ["game_die", "1f3b2", "dé, jeu", "die, game"],
  ["soccer_ball", "26bd", "ballon de foot", "soccer ball, football"],
  ["glasses", "1f453", "lunettes", "glasses"],
  ["ribbon", "1f380", "ruban, nœud", "ribbon, bow"],
  ["check_mark_button", "2705", "fait, coche", "done, check mark"],
  ["pushpin", "1f4cc", "punaise", "pushpin"],
  ["hundred_points", "1f4af", "cent, parfait", "hundred points, perfect"],
];

const rows: Array<[StickerCategory, Row[]]> = [
  ["nature", NATURE],
  ["food", FOOD],
  ["travel", TRAVEL],
  ["objects", OBJECTS],
];

export const CATALOG: readonly CatalogEntry[] = rows.flatMap(([category, list]) => list.map(([id, code, fr, en]) => ({ id, category, code, fr, en })));
